### ISSUE TITLE
怎么参与翻译？？

### ISSUE THREAD

**Issue by punkmonday** [waylau/spring-framework-4-reference#10]
最近也在读，如果可以，边读边翻译，但是怎么翻译啊？

**Comment by waylau** [comment]
@punkmonday   第五章 暂时还没有人领，你来不？

**Comment by waylau** [comment]
@punkmonday   哥们 ，确定要吗？

**Comment by punkmonday** [comment]
我试着翻译了一些，感觉比较别扭，英文水平差

**Comment by waylau** [comment]
@punkmonday  如果你之前没有 spring 的一些基础概念的话，对于一些专业术语的翻译是会比较辛苦的 。可以先看一些 spring 中文资料，而后再进行翻译。慢慢翻，翻译就是一个学习积累的过程
