### ISSUE TITLE
加油啦版主

### ISSUE THREAD

**Issue by phxism** [waylau/spring-framework-4-reference#14]
已经把Spring Data 的好几本官方pdf看完了，英文还算能懂可是看到SpringFramework 的八百多页英文我看到III. Core Technologies真是越来越吃力了,英文比其他的文档难懂啊。希望楼主加油啦，如果年能出书我也愿意买一本来看

**Comment by waylau** [comment]
@phxism   工程确实好浩大啊》～但我会继续努力。～感谢您的支持》～
