### ISSUE TITLE
还有另外的几个Spring4中文翻译项目，是否考虑一起合作呢

### ISSUE THREAD

**Issue by linfuyan** [waylau/spring-framework-4-reference#16]
我发现了以下几个 spring4 的翻译项目

https://github.com/b2gats/stone-docs
https://sunrh.gitbooks.io/spring4-reference-chinese
https://waylau.gitbooks.io/spring-framework-4-reference/content/
http://git.oschina.net/free/spring-framework-reference

目前为止对比了一下，这几个项目都不全。

是不是可以考虑一起来翻，不浪费人力。

**Comment by waylau** [comment]
@linfuyan  看了下这几个项目，前面两个基本没什么内容。后面2个都是我有份参与的，第三个项目就是本项目的 gitbook 版本，其中最后一个项目是在osc 上发起的，还组建了专门的群做讨论，当时参与的人也挺多，也分配了任务下去，但看实际完成率效果不是很好。
原因
1. spring 文档 工程浩大
2. 参与的人都是自发行为，实际上很难保证参与的力度

我这边当然是希望多多人参与进来。但开源这个事，真心是靠自觉的了。

**Comment by linfuyan** [comment]
第一个项目其实内容蛮多的，只是给写在了一个文档里面。具体的内容我没有细看。

你说的 spring 文档工程浩大，这个问题确实是大问题。我在想有没有可能先逐章拆解下来，比如说37章，先分成37个小翻译项目，逐个完成。这样，就不会因为工程量很大，一下子人不齐导致相互影响。

**Comment by waylau** [comment]
@linfuyan  还有一个问题，spring 更新频率好高，其中的目录结构都改了好多，所以很多章节变动好大。

这也是比较郁闷的地方，我们翻译的速度跟不上他更新的速度了。。

**Comment by linfuyan** [comment]
哦 ，原来这样。我今天看完你上面的回复，特意又看了一下 Spring 文档中的章节，再比对大家翻译的部分，我觉得有一些重点的部分其实应该是不会有多大变化的。比如其中的核心技术那块。这些部分我觉得比较重要，其他的可能就是按需翻就好。

**Comment by sagomilk** [comment]
@waylau   按照新版的目录提交了个pull request

**Comment by waylau** [comment]
@sagomilk   已经合并，感谢！
