### ISSUE TITLE
一个识别字

### ISSUE THREAD

**Issue by linzy410** [waylau/spring-framework-4-reference#17]
第16页
原文：
例如：把一个数据库连接**已**参数的形式传到一个对象的结构方法里面而不是在那个
对象内部自行创建一个连接

已 -> 以

**Comment by waylau** [comment]
@linzy410   你这个 “16 页 ” 是指的哪个页面 ？实在找不到了。你能把页面的路径 或者 章节名称发上来吗？麻烦了。

**Comment by linzy410** [comment]
pdf的16页

**Comment by linzy410** [comment]
https://github.com/waylau/spring-framework-4-reference/blob/master/I.%20Overview%20of%20Spring%20Framework/2.1.%20Dependency%20Injection%20and%20Inversion%20of%20Control.md

**Comment by waylau** [comment]
@linzy410  已经修复。感谢！
