### ISSUE TITLE
目前未翻译的章节，能否先放上英文原文

### ISSUE THREAD

**Issue by teclxl** [waylau/spring-framework-4-reference#18]
这样我就可以直接用这里当完整的参考手册了。
srping官方的参考文档实在是太大，没有快速目录导航的时候只能当做普通书籍而不是参考手册。

**Comment by waylau** [comment]
@teclxl  首先感谢你的建议。其次，由于本参考手册，完全是才用markdown 格式手工编排的，与英文原版并非同个文件格式和组织方式，故不能直接放到本项目。见谅

若想看原文，直接异步至http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/

**Comment by linesh-simplicity** [comment]
有现成的在线工具可以将html转成markdown，可以直接把Spring官网上的文档粘贴过去，直接生成markdown。或者可以使用一些npm的库，比如html-md等。

如果是要把markdown放到各个章节里面，写些脚本应该就可完成。

**Comment by wizardforcel** [comment]
比如说这个库[to-markdown](https://github.com/domchristie/to-markdown)，既可以编程调用，也可以手动交互。

**Comment by linesh-simplicity** [comment]
@wizardforcel 啊，我翻译Spring MVC文档的时候还搜到过你的仓库呢
