### ISSUE TITLE
3.1 Spring IOC 容器和Beans的介绍

### ISSUE THREAD

**Issue by Ron-Zheng** [waylau/spring-framework-4-reference#21]
本章主要包含了Spring framework 中控制反转规则（IOC）的实现。IOC也就是被大家所熟知的依赖注入（DI）。他是一个对象定义他的依赖的一个过程，所谓依赖，就是和它一起工作的对象，这个过程只能通过构造函数的参数，工厂方法的参数，或者已经被构造或者从工厂方法返回的对象的setter方法设置其属性来实现。然后容器在创建Bean时注入这些依赖。这个过程从根本上来讲是反向的，由于bean自己控制实例，或者直接通过类的结构，类似于服务定位机制的模式来定位他的依赖。
org.springframework.beans和org.springframework.context包是Spring Framework’s IoC容器的根本。BeanFactory接口提供了管理任何对象类型的先进的配置机制。 ApplicationContext是BeanFactory的子接口。 ApplicationContext使得和Spring的AOP功能集成变得更简单；添加了信息资源处理（国际化中使用），事件发布；还添加了应用程序层的特殊上下文 ，如用于web应用程序的WebApplicationContext。
简而言之，BeanFactory 提供了配置框架和基础功能，ApplicationContext添加了更多企业及特定的功能。ApplicationContext是BeanFactory的完整超集，本章ApplicationContext仅仅只是用来描述Spring IOC容器。更多关于使用BeanFactory代替ApplicationContext的信息，请参考3.16章节（The BeanFactory）。
在Spring中，形成应用程序骨架的对象和被Spring IOC容器所管理的对象称为Beans。一个Bean就是一个被实例化，被装配，被Spring IOC所管理的对象。此外，bean 就是你应用程序中诸多对象之一。Bean和Bean的依赖被容器所使用的配置元数据所反射。

**Comment by waylau** [comment]
@Ron-Zheng  感谢，已经修正
