### ISSUE TITLE
目录变更

### ISSUE THREAD

**Issue by byp5303628** [waylau/spring-framework-4-reference#25]
现在核心技术（Core Technologies）已经从第七章开始了，要不调整下目录吧，否则后续翻译改标题的名字会产生很多麻烦

**Comment by waylau** [comment]
@byp5303628   该目录的工作量有点大啊。而且，每次 spring  更新 都可能造成目录的变更。不知有无啥好的解决方案？

**Comment by wizardforcel** [comment]
@waylau 最好以一个版本的目录为准，暂时不要更新。

**Comment by byp5303628** [comment]
@waylau 确实不知道，我之前看的跟你的版本其实是一致的，每次维护这个名字什么的其实也蛮繁琐的，如果不动的话拿就先慢慢来吧，很多东西完成了再统一弄也可以

**Comment by waylau** [comment]
其实，我在第I  和 II 部分已经作了修改，及在目录上 不在显示章节序号。当然，事件的源文件可能还是有序号的（也可能不需要，如果文件名重名的时候，就需要），但还是应当弱化序号。这样，后面增加的内容，只需要在 目录里面插入相应的位置即可。
 


不知道，这样大家是否接受？

**Comment by byp5303628** [comment]
觉得可以，那之后推送就仿照你前面的写法，就不在写标号了，实在是难以维护

**Comment by waylau** [comment]
@byp5303628  OK
