### ISSUE TITLE
IoC 的Dependencies 乱码了，怎么解决

### ISSUE THREAD

**Issue by China-jhl** [waylau/spring-framework-4-reference#32]

**Comment by waylau** [comment]
@China-jhl 

你是说这章节的内容乱码吗》？https://github.com/waylau/spring-framework-4-reference/blob/master/III.%20Core%20Technologies/Dependencies.md

我看了下，是好的，没有乱啊

**Comment by byp5303628** [comment]
@waylau 估计是看Gitbook上面出现了乱码吧，我修一下吧，Dependcy和Bean Scope是我添加的，估计是因为本地是GBK的原因

**Comment by byp5303628** [comment]
@waylau ,merge 了关闭即可

**Comment by waylau** [comment]
@China-jhl   thx ~
