### ISSUE TITLE
为什么gitbook上不提供pdf下载。。。

### ISSUE THREAD

**Issue by EarthChen** [waylau/spring-framework-4-reference#38]
为什么gitbook上不提供pdf下载。。。访问真的蛮慢的啊

**Comment by byp5303628** [comment]
访问是有点慢的，但是肯定提供pdf下载的

**Comment by byp5303628** [comment]
@EarthChen 
访问该地址：
https://www.gitbook.com/book/waylau/spring-framework-4-reference/details
然后下载即可

**Comment by wizardforcel** [comment]
<https://www.gitbook.com/download/pdf/book/waylau/spring-framework-4-reference>

**Comment by EarthChen** [comment]
看着不完整啊 才133页 有完全版嘛  求4以上的翻译好的文档啊  英语渣渣没办法啊。。。。。

**Comment by waylau** [comment]
@EarthChen 这个翻译项目还是工程很浩大的，需要大家一起努力。目前，还没有完全完成，所以难免有些章节是没有的。暂时没有完整版本。期待您的参与！
